-- Catalogos usados por el import de bitacoras historicas (0017). Idempotente.

insert into categorias_mesa (nombre) values
  ('/Mediport (Tramites Electronicos)'),
  ('/Mediport (Tramites Electronicos)/API Servicios Portuarios'),
  ('/Mediport (Tramites Electronicos)/Accesos'),
  ('/Mediport (Tramites Electronicos)/Aduana'),
  ('/Mediport (Tramites Electronicos)/Buques'),
  ('/Mediport (Tramites Electronicos)/Buques/Planeación'),
  ('/Mediport (Tramites Electronicos)/Buques/Programación de Buques'),
  ('/Mediport (Tramites Electronicos)/Cabotaje'),
  ('/Mediport (Tramites Electronicos)/Carga'),
  ('/Mediport (Tramites Electronicos)/Liberacion de Automoviles'),
  ('/Mediport (Tramites Electronicos)/Pagos'),
  ('/Mediport (Tramites Electronicos)/Portal de Facturación'),
  ('/Mediport (Tramites Electronicos)/Portal de Facturación/Complemento de pago'),
  ('/Mediport (Tramites Electronicos)/Portal de Facturación/Facturas'),
  ('/Mediport (Tramites Electronicos)/Portal de Facturación/Facturas Obras'),
  ('/Mediport (Tramites Electronicos)/Portal de Facturación/Validación de CFDI'),
  ('/Mediport (Tramites Electronicos)/Servicio Web Automoviles'),
  ('/Mediport (Tramites Electronicos)/Solicitud de Contrato de Prestadores'),
  ('/Obras Externos'),
  ('/Operaciones/Edificio de Operaciones/Planta Baja'),
  ('/Seguridad de la Información/Reactivacion de usuario anterior'),
  ('/Seguridad de la Información/Restablecer usuario o contraseña Integral'),
  ('/Seguridad de la Información/Solicitud de privilegios/Integral'),
  ('/Seguridad de la Información/Solicitud de privilegios/Mediport'),
  ('/Seguridad de la Información/Solicitud de privilegios/PIS'),
  ('/Seguridad de la Información/Solicitud de privilegios/SIIP'),
  ('/Servicios'),
  ('/Servicios/Correo Electrónico'),
  ('/Servicios/Sitio WEB Público'),
  ('/Sistemas'),
  ('/Sistemas/Integral'),
  ('/Sistemas/Nuevos Ingresos'),
  ('/Sistemas/Nuevos Ingresos/SIIP- nuevo ingreso'),
  ('/Sistemas/Obras (Extranet)'),
  ('/Sistemas/SIIP Activo Fijo'),
  ('/Sistemas/SIIP Almacenes'),
  ('/Sistemas/SIIP Almacenes/Libreación de Vehiculos'),
  ('/Sistemas/SIIP Almacenes/Manifiestos'),
  ('/Sistemas/SIIP Almacenes/Mercancías de Exportación'),
  ('/Sistemas/SIIP Bancos'),
  ('/Sistemas/SIIP Cesion Parcial'),
  ('/Sistemas/SIIP Compras'),
  ('/Sistemas/SIIP Compras/Acceso al modulo de Compras'),
  ('/Sistemas/SIIP Compras/Cotizaciones'),
  ('/Sistemas/SIIP Compras/Cuentas por Pagar'),
  ('/Sistemas/SIIP Compras/Facturas'),
  ('/Sistemas/SIIP Compras/Facturas Obra'),
  ('/Sistemas/SIIP Compras/Facturas Obra/Ajuste Monto Factura'),
  ('/Sistemas/SIIP Compras/Facturas Obra/Habilitacion de folios'),
  ('/Sistemas/SIIP Compras/Facturas/Sustitucion CFDI'),
  ('/Sistemas/SIIP Compras/Investigación de Mercado'),
  ('/Sistemas/SIIP Compras/Licitaciones'),
  ('/Sistemas/SIIP Compras/Movimientos de Almacen'),
  ('/Sistemas/SIIP Compras/Notas de Crédito'),
  ('/Sistemas/SIIP Compras/Pagos'),
  ('/Sistemas/SIIP Compras/Pedido'),
  ('/Sistemas/SIIP Compras/Pedidos'),
  ('/Sistemas/SIIP Compras/Pedidos/Cambio de Fecha'),
  ('/Sistemas/SIIP Compras/Recepción de Materiales (embarque)'),
  ('/Sistemas/SIIP Compras/Requisiciones'),
  ('/Sistemas/SIIP Compras/Requisiciones/Cambio de Estado'),
  ('/Sistemas/SIIP Compras/Requisiciones/Cambio de Fecha'),
  ('/Sistemas/SIIP Compras/Servicios Generales'),
  ('/Sistemas/SIIP Contabilidad'),
  ('/Sistemas/SIIP Contabilidad/Aplicacion de Pólizas'),
  ('/Sistemas/SIIP Contabilidad/Captura de pólizas'),
  ('/Sistemas/SIIP Contabilidad/Consultas'),
  ('/Sistemas/SIIP Contabilidad/Pólizas Armonizadas'),
  ('/Sistemas/SIIP Control de Contratos'),
  ('/Sistemas/SIIP Facturación'),
  ('/Sistemas/SIIP Facturación
/Depósitos en garantía'),
  ('/Sistemas/SIIP Facturación/Almacenaje'),
  ('/Sistemas/SIIP Facturación/Aprovechamiento'),
  ('/Sistemas/SIIP Facturación/Atraque'),
  ('/Sistemas/SIIP Facturación/Cobros'),
  ('/Sistemas/SIIP Facturación/Concesiones'),
  ('/Sistemas/SIIP Facturación/Cuentas por Cobrar'),
  ('/Sistemas/SIIP Facturación/Depósitos en garantía'),
  ('/Sistemas/SIIP Facturación/Muellaje'),
  ('/Sistemas/SIIP Facturación/Notas de Crédito'),
  ('/Sistemas/SIIP Facturación/Otros Ingresos'),
  ('/Sistemas/SIIP Facturación/Puerto'),
  ('/Sistemas/SIIP Facturación/Reportes'),
  ('/Sistemas/SIIP Obras'),
  ('/Sistemas/SIIP Obras/Cambio de proyectos de inversion'),
  ('/Sistemas/SIIP Obras/Contratos'),
  ('/Sistemas/SIIP Obras/Estimaciones'),
  ('/Sistemas/SIIP Oficialia de partes'),
  ('/Sistemas/SIIP Operaciones'),
  ('/Sistemas/SIIP Operaciones/Arribos y Zarpes de Buques'),
  ('/Sistemas/SIIP Operaciones/Reportes'),
  ('/Sistemas/SIIP Recursos Humanos/Capacitacion'),
  ('/Sistemas/SIIP Trámites y Solicitudes'),
  ('/Sistemas/SIIP Trámites y Solicitudes/Justificación de Incidencias'),
  ('/Sistemas/SIIP Trámites y Solicitudes/Recibos de Nomina'),
  ('/Sistemas/SIIP Trámites y Solicitudes/Vacaciones'),
  ('/Sistemas/SIIP Viáticos'),
  ('/Sistemas/SIIP Viáticos/Caja Chica'),
  ('/Sistemas/SIRE'),
  ('/Sistemas/Tablero Presupuestal'),
  ('/Sistemas/Tablero de Carga'),
  ('Gosset Laborie, Maria Fernanda'),
  ('Sistemas/SIIP Compras/Pedidos/Cambio de Fecha'),
  ('comprobación viáticos 4897')
on conflict (nombre) do nothing;

insert into solicitantes_mesa (nombre) values
  ('Acosta Ramos, Yahaira Alin'),
  ('Aguilar Heredia, Juan de Dios'),
  ('Alejandro Hernandez Arcos / Reyes Cicero, Sergio'),
  ('Altamirano Landa, Alessandra'),
  ('Anell Ortiz, Enrique'),
  ('Arresola Martínez, Alejandro'),
  ('Atencio Casanova, Samuel'),
  ('Bautista Bello, Abigail'),
  ('Bautista Martínez, Gabriela Yuritzi'),
  ('Becerra Reyes, Jose Aubert'),
  ('Belchez Notni, Mario'),
  ('Bernal Hernández, Sarha Melissa'),
  ('Bravo Bravo, Yadira'),
  ('Briano Rangel, Isaac Giovanni'),
  ('Caballero Cortez, Violeta'),
  ('Calva Hernández, Juan Manuel'),
  ('Campos Garcia, Reyna Alejandra'),
  ('Cancino Aguirre, Nardy Neyrot'),
  ('Cano Velazquez, Karla Victoria'),
  ('Cano Velázquez, Karla Victoria'),
  ('Carballido Brenis, Barbara'),
  ('Carmona Najera, Joseline'),
  ('Carmona Nájera, Joselin'),
  ('Carrion Lechuga, Olivia'),
  ('Castillejos Lugo, Oscar'),
  ('Castillo Morales, Jennifer'),
  ('Castro Arano, Beatriz'),
  ('Cedillo Lara, Karla Maria'),
  ('Chavez Ramos, Selene'),
  ('Chavez Trujillo, Magda Isabel'),
  ('Colorado García, Inocente'),
  ('Colorado Solano, Susana'),
  ('Contreras Martínez, Karla Teresa'),
  ('Correa García, Abril Estefania'),
  ('Cruz González, Gerardo'),
  ('Cuervo Bermudez, Darian Alexa'),
  ('De Paz Ortiz, Angel Isaac'),
  ('Deceano Ocampo, Isidro'),
  ('Diaz Mendez, Guadalupe'),
  ('Diaz Ortiz, Oscar'),
  ('Dominguez Barros, JoseLuis'),
  ('Domínguez Vera, Michelle'),
  ('Durante Crivelli, Alessandra'),
  ('Díaz Centurion, Karla Fabiola'),
  ('Díaz Centurión, Karla Fabiola'),
  ('Díaz Ortíz, Oscar'),
  ('Esparza Cardona, Cesar Enrique'),
  ('Espinosa López, Nora Luisa'),
  ('Fernández Velázquez, Málory Alanis'),
  ('Fierro Escobedo, Rosa Isela'),
  ('Flores Bretón, Daniel José'),
  ('Flores Lopez, Patricia Elizabeth'),
  ('Flores Saldaña, Andrea'),
  ('Gallardo Reyes, Efrain'),
  ('Garcia Lopez, Elvira del Carmen'),
  ('Garcia Saldaña, Adrian'),
  ('García Contreras, Kaleb Al Aissa'),
  ('García González, María Sandra Luz'),
  ('García Sosa, Samuel'),
  ('General, Director'),
  ('Gerrero Serrano, Diego'),
  ('Gomez Rodriguez, Ricardo'),
  ('Goméz Rodríguez, Ricardo'),
  ('Gonzalez Cerezo, Cristina'),
  ('Gonzalez Ramirez, Jeimmy'),
  ('Gonzalez Rosas, Jorge Israel'),
  ('González Cadena, David Alfonso'),
  ('González Cerezo, Cristina'),
  ('González Dominguez, Daniel'),
  ('González Martínez, Francisco de Jesus'),
  ('González Vargas, Marilyn Monserrath'),
  ('González Vidrio, Isis'),
  ('Gosset Laborie, Maria Fernanda'),
  ('Gozo Avila, Jesus Guillermo'),
  ('Gutierrez Fernández, Lluvia del Carmen'),
  ('Gutierrez Luna, Candida'),
  ('Gutierrez Uscanga, Juan Pedro'),
  ('Guzman Guzman, Nohemi'),
  ('Gómez Caro, Karen Rocio'),
  ('Gómez Hernández, Carlos Ignacio'),
  ('Haruel Aguirre, Lizbeth'),
  ('Hernández Arcos, Alejandro'),
  ('Hernández Chacha, Valeria'),
  ('Hernández Cornejo, Angelli'),
  ('Hernández Galván, Pamela Estefanía'),
  ('Hernández Hernández, Genaro'),
  ('Hernández Matías, Raúl Antonio'),
  ('Hernández Segura, Mayra Celeste'),
  ('Illescas Guevara, Miguel Angel'),
  ('Illescas Guevara, Miguel Ángel'),
  ('Isidoro Cervantes, Pamela'),
  ('Jimenez, Phecda Monserrat'),
  ('Lagos Ambrosio, Rogelio'),
  ('Lajud Hernández, Aida'),
  ('Landeros Hernández, Brenda Marlem'),
  ('Lara Cruz, Amairany'),
  ('Lara Guatemala, Kelly Anairam'),
  ('Laurent García, Ximena'),
  ('León Martínez, María Fernanda'),
  ('Limas Barragan, Francisco'),
  ('Limón Acevedo, Rodolfo'),
  ('Limón Rojas, Felipe David'),
  ('Loperena Dominguez, Sergio Adolfo'),
  ('López Muñoz, Laura'),
  ('López Paz, Adriana Mar'),
  ('Machado Piña, Hilda'),
  ('Madrazo Millán, Carolina Gudalupe'),
  ('Marquez Berruecos, Ivette Teresa'),
  ('Martinez Hernández, Jorge'),
  ('Martinez Lopez, Elizabeth'),
  ('Martínez Alemán, Fernando'),
  ('Martínez Guerola, Héctor Manuel'),
  ('Martínez Pardo, Missael Abraham'),
  ('Martínez Pastor, Joseline'),
  ('Melo Escarela, Luis Angel'),
  ('Mendoza Castillo, Marisa Trinidad'),
  ('Mendoza Ríos, Verania Lizette'),
  ('Molina Hernández, Javier Alexis'),
  ('Molina Montiel, Miriam del Carmen'),
  ('Monroy Leon, Luis Fernando'),
  ('Monsivais Castillo, Roman Alexander'),
  ('Montero Otal, Elisa Margarita'),
  ('Mora Utrera, Luis Alberto'),
  ('Morales Hernandez, Oscar Hilario'),
  ('Morales Hernández, Oscar Hilario'),
  ('Morales Mavil, Jorge Antonio'),
  ('Morales Tronco, Diana Isabel'),
  ('Moreno Cobix, Miguel Angel'),
  ('Morfinez Anaya, Jose Gabriel'),
  ('Morfinez Anaya, José Gabriel'),
  ('Morlet Cienfuegos, Luis'),
  ('Murillo Vazquez, Patricia'),
  ('Muñoz Ayala, Karla Lorena'),
  ('Muñoz Cancino, Pablo'),
  ('Muñoz Morales, Alejandra de Jesus'),
  ('Olvera Martinez, Yazmin'),
  ('Ortiz Morales, Cesar'),
  ('Padrón Ramón, Juan Vicente'),
  ('Palacios Herrera, Viridiana Guadalupe'),
  ('Palmeros Mayo, Jorge Alfredo'),
  ('Piña Pereda, Ximena'),
  ('Priego López, Valeria Guadalupe'),
  ('Pulido López, Rey David'),
  ('Pérez Hernández, Joel Adrian'),
  ('Pérez Ramírez, Nery Elidé'),
  ('Pérez Villa, Montserrat del Carmen'),
  ('Quiroz Mártinez, María del Carmen'),
  ('Ramos Cházaro, Efrén'),
  ('Ramos Leyva, José Manuel'),
  ('Ramos Morales, Ismael'),
  ('Ramírez Dimas, Cristina'),
  ('Redondo Reyes, Adelita'),
  ('Reyes Cicero, Sergio'),
  ('Reyes Jiménez, Jocelyn Aurora'),
  ('Reyes Sánchez, Yamile'),
  ('Reyes, Alfredo'),
  ('Robledo Navarrete, Dolores'),
  ('Rodriguez Diaz, Sol de los Angeles'),
  ('Ronces Rodríguez, Elias Armando'),
  ('Rosas Toledano, Edgar Omar'),
  ('Ríos Marcial, Jonathan'),
  ('Saavedra Lara, Silvia Dariana'),
  ('Salazar Loredo, Roberto'),
  ('Salgado Navarro, Agustin'),
  ('Sanchez Solano, Perla'),
  ('Santiago Peña, Laryssa Guadalupe'),
  ('Sardiña Aguirre, Eira Danae'),
  ('Sarmiento Aquino, Adriana Monserrat'),
  ('Serena Silván, Cinthya Araceli'),
  ('Serrano Berriozabal, Jose Luis'),
  ('Simonín Baldwin, Ana Laura'),
  ('Somarriba Uscanga, Isis Grecia de los Angeles'),
  ('Suarez Herrera, Jose Gabriel'),
  ('Sánchez Domínguez, Laura Irene'),
  ('Sánchez Lagunes, Nataly'),
  ('Sánchez Ruiz, Francisco'),
  ('Sánchez Valenzuela, Cesar'),
  ('Toris Fabian, Samuel'),
  ('Trujillo Melchor, Omar'),
  ('Valentin Aguirre, Jarumi de los Angeles'),
  ('Vargas Díaz, Leonardo'),
  ('Vargas Zapata, Maria Isabel'),
  ('Vega Martínez, Cristian'),
  ('Velazquez Rodriguez, Sandra Luz'),
  ('Verdejo Grajales, Jonathan'),
  ('Villalba Rojas, Briseiri Aylin'),
  ('Vizcarra Barra, Daniel Benito'),
  ('Vázquez Ruiz, Ileana'),
  ('Zamora Martinez, Ana Laura'),
  ('de Trafico Maritimo, Centro de Control'),
  ('de la Cruz Castillo, Alejandra'),
  ('p')
on conflict (nombre) do nothing;

insert into resolutores_mesa (nombre) values
  ('Andrade Malpica, Hector Ulises'),
  ('Gallardo Lopez, Luis Fernando'),
  ('Hernandez Gonzalez, Gabriel'),
  ('Nieto Torres, Atzimba del Rosario'),
  ('Sandria Pérez, Ángel Manuel'),
  ('Suárez Vázquez, Héctor Andrés')
on conflict (nombre) do nothing;

insert into ventanas_mesa (nombre) values
  ('ACTA DE PROGRAMACION'),
  ('ACTIVOS FIJOS'),
  ('ANTICIPOS DEL CONTRATO'),
  ('API CARGA'),
  ('API SERVICIOS'),
  ('ARRIBO DE BUQUES'),
  ('ARRIBO O ZARPE DE BUQUE'),
  ('ASIGNACION DE VACACIONES'),
  ('ASIGNACION VACACIONES'),
  ('AVISOS'),
  ('BANCOS'),
  ('BITACORA CCTM'),
  ('BUQUES'),
  ('CAJA CHICA / FONDO REVOLVENTE'),
  ('CALCULO DE ESTIMACIONES'),
  ('CALCULO ESTIMACIONES'),
  ('CAMBIO DE FECHA'),
  ('CAMBIO DE FECHAS'),
  ('CAMBIO DE PROVEEDOR'),
  ('CAMBIOS DE FECHA'),
  ('CANCELACION DE FACTURAS'),
  ('CANCELACION FACTURAS'),
  ('CAPTURA DE FIANZAS Y CONTRAPRESTACIONES'),
  ('CAPTURA Y CONSULTA DE CONTRATOS'),
  ('CARGAR FACTURAS'),
  ('CASETAS OPERATIVAS'),
  ('CATALOGO DE DEPARTAMENTOS'),
  ('CATALOGO DE PROVEEDORES'),
  ('CFDI'),
  ('CLIENTES'),
  ('COBROS'),
  ('COMPLEMENTO DE PAGO'),
  ('COMPLEMENTOS'),
  ('COMPLEMENTOS DE PAGO'),
  ('COMPRAS'),
  ('COMPROBACION DE FONDO REVOLVENTE'),
  ('COMPROBACION DE VIATICOS'),
  ('COMPROBACION DE VIÁTICOS'),
  ('COMPROBACION DE VÍATICOS'),
  ('COMPROBACION VIATICOS'),
  ('COMPROBACIONDEVIATICOS'),
  ('COMPROBACIÓN DE VIÁTICOS'),
  ('COMPROBACIÓN DE VIÁTICOS / CAJA CHICA'),
  ('CONCENTRADO DE OBRAS'),
  ('CONSULTA DE CONTRATOS'),
  ('CONSULTA DE DOCUMENTOS'),
  ('CONSULTA DE REQUISICIONES EN TRAMITE'),
  ('CONSULTA DE VINS'),
  ('CONTABILIDAD'),
  ('CONTRATOS'),
  ('CONTRATOS CCPD'),
  ('CONTROL DE ACTIVO'),
  ('CONTROL DE CARGA'),
  ('CONTROL DE CASETAS OPERATIVAS'),
  ('CONTROL DE CONTRATOS'),
  ('CONVOCATORIAS DE LICITACIONES O INVITACIONES'),
  ('CORREO'),
  ('CORTE DE CAJA X TARIFA'),
  ('COTIZACIONES'),
  ('COTIZACIONES/PEDIDOS'),
  ('DEPOSITOS EN GARANTIA'),
  ('DETALLE DE COMPROBACION DE FONDO REVOLVENTE'),
  ('DETALLE DE COMPROBACION DE VIATICOS'),
  ('DETALLE DE FACTURACION DE VENTAS'),
  ('DETALLE DE FACTURAS'),
  ('DETALLE DE PAGOS'),
  ('DETALLE DE PAGOS DEL CONTRATO'),
  ('DETALLE MOVIMIENTO ALMACEN'),
  ('DETALLES DE PAGO DEL CONTRATO'),
  ('DETALLES DE PAGOS EL CONTRATO'),
  ('DIFERENCIAS SUA'),
  ('DISTRIBUCION DE CENTRO DE COSTOS'),
  ('DISTRIBUCION DE MONTOS PRESUPUESTALES ANUALES DEL CONTRATO'),
  ('DOCUMENTO SAM M3'),
  ('EMBARQUES'),
  ('ESTADO DE CONVOCATORIAS'),
  ('ESTADO DE LA ESTIMACION'),
  ('ESTADO DE SOLICITUDES DE CONTRATO'),
  ('ESTADO DE SOLICITUDES DEL CONTRATO'),
  ('ESTIMACIONES'),
  ('ESTIMACIONES PARA FINIQUITO'),
  ('ESTRUCTURA PROGRAMATICA'),
  ('EXPEDIENTE_BUQUE'),
  ('EXPORTACION DE FACTURAS'),
  ('EXPORTACION DE POLIZAS A CONTABILIDAD'),
  ('FACTURACION'),
  ('FACTURACION DE ATRAQUES'),
  ('FACTURACION DE CONCESIONES'),
  ('FACTURACION DE PUERTOS'),
  ('FACTURACION DE PUERTOS/FACTURACION DE ATRAQUE'),
  ('FACTURACION ELECTRONICA'),
  ('FACTURACION POR APROVECHAMIENTO'),
  ('FACTURACION X MUELLAJE DE MERCANCIA'),
  ('FACTURACION X MUELLAJE FERROVIARIO'),
  ('FACTURACIÓN ELECTRÓNICA'),
  ('FACTURAS'),
  ('FACTURAS DE ANTICIPO'),
  ('FACTURAS DE ANTICIPOS'),
  ('FACTURAS OBRA'),
  ('FACTURAS PENDIENTES'),
  ('FIRMAS/INTEGRAL'),
  ('FOLIOS DE SALIDA'),
  ('FOLIOS SALIDA'),
  ('FOLIOS_SALIDA'),
  ('FONDO REVOLVENTE'),
  ('GENERACION DE TRANSFERENCIAS'),
  ('INCIDENCIAS'),
  ('INDICADORES'),
  ('INFORME DE SALIDA'),
  ('INTEGRAL'),
  ('INTEGRAL/SIIP'),
  ('INVENTARIO'),
  ('INVENTARIOS'),
  ('INVESTIGACION DE MERCADO'),
  ('INVESTIGACION MERCADO'),
  ('INVESTIGACIONMERCADO'),
  ('INVESTIGACIÓN DE MERCADO'),
  ('JUSTIFICACION DE INCIDENCIA'),
  ('JUSTIFICACION DE INCIDENCIAS'),
  ('JUSTIFICACION DE INCIDENCIAS / SIIPV2'),
  ('JUSTIFICACIÓN DE INCIDENCIAS'),
  ('LICITACIONES'),
  ('LIQUIDACION DE PAGOS'),
  ('MANIFIESTOS'),
  ('MEDIPORT'),
  ('MEMORANDUM/SOLICITUDES DE CONTRATO'),
  ('MIS P3'),
  ('MODIFICACION DEL CONTRATO'),
  ('MODIFICACIONES AL CONTRATO'),
  ('MODIFICACIONES Al CONTRATO'),
  ('MODULO DE GASTOS A COMPROBAR'),
  ('MODULO TRAMITES Y SOLICITUDES/VIATICOS'),
  ('MOVIMIENTOS DE ALMACEN'),
  ('MOVIMINETOS DE ALMACEN X ENTRADAS/SALIDAS'),
  ('NETEO DE COMPLEMENTOS DE PAGOS'),
  ('NOTA DE CARGO'),
  ('NOTA DE CREDITO'),
  ('NOTAS DE CREDITO'),
  ('NOTAS DE OTRO DE INGRESO'),
  ('NOTIFICACIONES'),
  ('OBRAS'),
  ('OPERACION'),
  ('ORDEN DE COMPRA'),
  ('P3'),
  ('PAGOS'),
  ('PAGOS FUTUROS'),
  ('PAGOS PENDIENTES'),
  ('PEDIDO'),
  ('PEDIDOS'),
  ('PERSONAL RECINTO'),
  ('PERSONAS AUTIRIZADAS PARA FIRMAR CONTRATO'),
  ('PERSONAS AUTORIZADAS PARA FIRMAR CONTRATO'),
  ('POLIZA VS ESTRUCTURA PROGRAMATICA'),
  ('POLIZAS'),
  ('POLIZAS VS ESTRUCTURA PROGRAMATICA'),
  ('POLIZAS vs ESTRUCTURA PROGRAMATICA'),
  ('PORTAL CFDI'),
  ('PROGRAMACION DE BUQUES'),
  ('PROVEEDORES'),
  ('PROVEEDORES/ACREEDORES'),
  ('RECEPCION CFDI'),
  ('RECEPCION DE CFDI'),
  ('RECEPCION DE CFDIS'),
  ('RECEPCION DE FACTURAS'),
  ('RECEPCION DE MATERIALES'),
  ('RECEPCIÓN VIA MEDIPORT'),
  ('RECIBOS DE NOMINA'),
  ('REPORTE CFDI'),
  ('REPORTE DE CUENTAS POR COBRAR'),
  ('REPORTE DE CURSOS X EMPLEADO'),
  ('REPORTE DE POLIZAS'),
  ('REPORTE DIARIO DE REGISTRO DE BUQUES'),
  ('REPORTE FACTURACION'),
  ('REPORTE FACTURAS'),
  ('REPORTE OBRAS'),
  ('REPORTES'),
  ('REPORTES DE ANTICIPOS'),
  ('REQUISICION E INVESTIGACION DE MERCADO'),
  ('REQUISICION E INVESTIGACIONMERCADO'),
  ('REQUISICIONES'),
  ('REQUISICIONES E INVESTIGACION DE MERCADO'),
  ('REQUISICIONES E INVESTIGACIONMERCADO'),
  ('REQUISICIONES/INVESTIGACION DE MERCADO'),
  ('REQUISICIONES/PEDIDOS'),
  ('REQUISIONES'),
  ('SALIDAS DE ALMACEN'),
  ('SAM M3'),
  ('SIIP'),
  ('SIIP BANCOS'),
  ('SIIPV2'),
  ('SIIPv2'),
  ('SIPOT'),
  ('SIRE'),
  ('SOLICITUD DE CONTRATO'),
  ('SOLICITUD DE CONTRATOS'),
  ('SOLICITUD DE CONVENIO'),
  ('SOLICITUD DE VACACIONES'),
  ('SOLICITUD DE VIÁTICOS'),
  ('SOLICITUDDESALIDAS'),
  ('SOLICITUDES DE CONTRATO'),
  ('SOLICITUDES DE CONTRATOS'),
  ('SOLICITUDES DE CONVENIO'),
  ('SOLICITUDES DE CONVENIOS'),
  ('TABLERO CFDI'),
  ('TABLERO EXPEDIENTE BUQUE'),
  ('TABLERO MEDIPORT'),
  ('TARJA DE CARGA'),
  ('TIMBRADOR'),
  ('TRABAJOS ELECTRICOS'),
  ('TRAMITES ELECTRONICOS'),
  ('TRAMITES ELECTRÓNICOS'),
  ('TRAMITES ELECTRÓNICOS /AMPLIAR CONTRATO A EMPRESAS'),
  ('TRAMITES Y SOLICITUDES'),
  ('TRÁMITES ELECTRÓNICOS'),
  ('USUARIOS'),
  ('VACACIONES'),
  ('VALIDACION CFDI'),
  ('VALIDACION DE CFDI'),
  ('VALIDAR COMPLEMENTOS'),
  ('VALIDAR FACTURAS'),
  ('VERIFICACIÓN DE PRESUPUESTA'),
  ('VIATICOS')
on conflict (nombre) do nothing;

